import Head from 'next/head'

const HeadMeta = () => {
    return (
        <Head>
          <title>Nacho Zorra Bot</title>
          <meta charSet="utf-8" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;0,600;0,700;1,400&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet" />
        </Head>
    )
  }

  export default HeadMeta;
  